CREATE TABLE tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    name VARCHAR(255) NOT NULL,
    api_key VARCHAR(255) NOT NULL,
    plan VARCHAR(255) NOT NULL CHECK (plan IN ('FREE', 'BASIC', 'PRO')),
    requests_per_minute INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT UK3en99tewvbc4g3a7ou4mt1ono UNIQUE (api_key)
);

CREATE TABLE admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    tenant_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT uk_admin_users_email UNIQUE (email),
    CONSTRAINT fk_admin_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    tenant_id VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    campaign VARCHAR(255),
    status VARCHAR(30) NOT NULL CHECK (status IN ('NEW', 'AUTO_REPLIED', 'WAITING_CUSTOMER', 'QUALIFIED', 'CONVERTED', 'CLOSED')),
    CONSTRAINT uk_leads_tenant_id_phone UNIQUE (tenant_id, phone)
);

CREATE TABLE automation_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    tenant_id VARCHAR(255) NOT NULL,
    keyword VARCHAR(255),
    priority INTEGER NOT NULL,
    action_type VARCHAR(255) CHECK (action_type IN ('SEND_MESSAGE', 'TAG_LEAD', 'CHANGE_STATUS')),
    action_payload VARCHAR(2000)
);

CREATE TABLE processed_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    tenant_id VARCHAR(255) NOT NULL,
    message_id VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT UKd7upy4rj7oa1rg0iyosh5wp90 UNIQUE (tenant_id, message_id)
);

CREATE TABLE lead_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    tenant_id VARCHAR(255) NOT NULL,
    message_id VARCHAR(255) NOT NULL,
    lead_id BIGINT NOT NULL,
    direction VARCHAR(20) NOT NULL CHECK (direction IN ('INBOUND', 'OUTBOUND')),
    content VARCHAR(2000) NOT NULL,
    CONSTRAINT uk_lead_messages_tenant_id_message_id UNIQUE (tenant_id, message_id),
    CONSTRAINT FK2b5ldj1kyn9s3b0xwhcdqwpww FOREIGN KEY (lead_id) REFERENCES leads(id)
);

CREATE INDEX idx_rules_tenant_id ON automation_rules (tenant_id);
CREATE INDEX idx_rules_keyword ON automation_rules (keyword);

CREATE INDEX idx_leads_tenant_id_phone ON leads (tenant_id, phone);
CREATE INDEX idx_leads_tenant_id_status ON leads (tenant_id, status);

CREATE INDEX idx_lead_messages_lead_created_at ON lead_messages (lead_id, created_at);
CREATE INDEX idx_lead_messages_tenant_id_message_id ON lead_messages (tenant_id, message_id);
