spring:
  application:
    name: lead-api

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

whatsapp:
  verify-token: ${WHATSAPP_VERIFY_TOKEN}
  app-secret: ${WHATSAPP_APP_SECRET}
